/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.vista;

/**
 *
 * @author LENOVO
 */
public class MainVista extends javax.swing.JFrame {

    /**
     * Creates new form MainVista
     */
    public MainVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSimuladorMain = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEquipoMain = new javax.swing.JButton();
        btnJugadorMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 250));

        btnSimuladorMain.setText("Simulador");
        btnSimuladorMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimuladorMainActionPerformed(evt);
            }
        });

        jLabel1.setText("Bienvenidos!!");

        btnEquipoMain.setText("Equipo");
        btnEquipoMain.setAlignmentX(100.0F);
        btnEquipoMain.setAlignmentY(100.0F);
        btnEquipoMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipoMainActionPerformed(evt);
            }
        });

        btnJugadorMain.setText("Jugadores");
        btnJugadorMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugadorMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnEquipoMain)
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnJugadorMain)
                        .addGap(87, 87, 87)
                        .addComponent(btnSimuladorMain)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEquipoMain)
                    .addComponent(btnJugadorMain)
                    .addComponent(btnSimuladorMain))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimuladorMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimuladorMainActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RegistarPartida registroPartida = new RegistarPartida();
        registroPartida.setVisible(true);
    }//GEN-LAST:event_btnSimuladorMainActionPerformed

    private void btnEquipoMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipoMainActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RegistroEquipo registroEquipo = new RegistroEquipo();
        registroEquipo.setVisible(true);
    }//GEN-LAST:event_btnEquipoMainActionPerformed

    private void btnJugadorMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugadorMainActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RegistrarJugadores registroJugador = new RegistrarJugadores();
        registroJugador.setVisible(true);
    }//GEN-LAST:event_btnJugadorMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEquipoMain;
    private javax.swing.JButton btnJugadorMain;
    private javax.swing.JButton btnSimuladorMain;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
